-- =============================================================================
-- One-time database initialisation.
--
-- The official PostgreSQL entrypoint runs every *.sql in /docker-entrypoint-initdb.d
-- EXACTLY ONCE — on the very first start, while the data directory is empty. It is
-- never re-run, so editing this file after the first boot has no effect. To apply a
-- change here you must destroy the postgres_data volume, which destroys the database.
--
-- It runs against POSTGRES_DB as POSTGRES_USER, so no \connect is needed.
--
-- IMPORTANT: this file does NOT create tables. Flyway owns the schema
-- (backend/src/main/resources/db/migration) and runs at application startup with
-- ddl-auto=validate. Creating anything here would drift from the migration history
-- and cause Hibernate's schema validation to fail on boot.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- pg_stat_statements.
--
-- postgresql.conf loads the library into every backend, but the VIEW only exists in
-- a database where the extension has been created — and this is the only moment we
-- get to do that automatically. Without it, the single most useful diagnostic during
-- an incident ("what is the database actually spending its time on") is unavailable
-- until someone remembers to run this by hand at 3am.
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

-- ---------------------------------------------------------------------------
-- Privilege surface.
--
-- Unlike the MySQL stack this replaced, there is no separate root account: initdb
-- creates exactly one role (POSTGRES_USER) and it owns this database and is a
-- superuser. That is a genuine reduction in isolation and it was accepted knowingly:
--
--   * Flyway needs full DDL (CREATE, ALTER, DROP, INDEX) to apply migrations at
--     startup, so a SELECT/INSERT/UPDATE/DELETE-only account cannot boot the app.
--   * Splitting owner from application role means ALTER DEFAULT PRIVILEGES for every
--     object class, re-asserted after every migration that creates a table — a
--     standing source of "works locally, 500s in production".
--
-- What makes it acceptable is the same thing that made the old MySQL grant
-- acceptable: this container publishes no port, sits on a Docker network declared
-- `internal: true` (no default gateway, so no route to the internet even from inside
-- it), and nothing reaches it but the API container and the backup job.
--
-- The one thing that IS worth closing is the PUBLIC schema default. Historically any
-- role could create objects in `public`; PostgreSQL 15+ revokes that by default, and
-- this asserts it explicitly so the posture does not depend on the image's version.
-- ---------------------------------------------------------------------------
REVOKE CREATE ON SCHEMA public FROM PUBLIC;

-- ---------------------------------------------------------------------------
-- Statement timeout for interactive sessions is deliberately NOT set here.
--
-- A database-wide ALTER DATABASE ... SET statement_timeout would also apply to the
-- API's connections, and would kill the CSV bulk import and the nightly invoice
-- sweep, both of which are legitimately long-running. Set it per session when doing
-- manual surgery:  SET statement_timeout = '30s';
-- ---------------------------------------------------------------------------
