-- =============================================================================
-- PG Manager -- consolidated PostgreSQL baseline.
--
-- This single file replaces the 31 MySQL migrations V1..V31 that preceded the
-- move to PostgreSQL. It is the NET schema: what those migrations left behind
-- after V24 dropped 15 dead tables + 4 views and V29 dropped subscription_plan.
-- The originals are kept, unmodified and off the classpath, in
-- backend/db/legacy-mysql/ as a historical record.
--
-- Why consolidated rather than 31 ported files: the MySQL flyway_schema_history
-- cannot carry across engines, so nothing is gained by replaying DDL that later
-- migrations undo. Every design decision recorded in the old files' comments has
-- been carried forward into the comments here.
--
-- MySQL -> PostgreSQL type mapping applied throughout:
--     BIGINT AUTO_INCREMENT  ->  BIGINT GENERATED BY DEFAULT AS IDENTITY
--     DATETIME(6) / DATETIME ->  TIMESTAMP(6)          (no time zone, as before)
--     TINYINT(1)             ->  BOOLEAN
--     LONGTEXT               ->  TEXT
--     JSON                   ->  JSONB
--     CHAR(n)                ->  VARCHAR(n)            (see note below)
--     inline INDEX/KEY       ->  a separate CREATE INDEX
--     UNIQUE KEY name (...)  ->  CONSTRAINT name UNIQUE (...)
--
-- CHAR(n) -> VARCHAR(n) is the one deliberate deviation. PostgreSQL's CHAR is
-- blank-padded, so a bpchar column compared against a bound VARCHAR parameter
-- brings padding semantics into queries that never had them under MySQL. The
-- three affected columns (billing_account.currency_code, expense_budget.
-- budget_month, staff_salary_payment.pay_month) always hold exactly-n-character
-- values, so VARCHAR is identical in practice and has no padding trap.
--
-- ddl-auto is `validate`, so the 19 tables that have a JPA @Entity must match
-- their mapping exactly. The remaining tables are JdbcTemplate-only and are not
-- tracked by Hibernate.
-- =============================================================================


-- =============================================================================
-- SECTION 1 -- Party / facility backbone
-- =============================================================================

CREATE TABLE party (
    party_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_type_id VARCHAR(30) NOT NULL,
    status        VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at    TIMESTAMP(6) NOT NULL,
    updated_at    TIMESTAMP(6) NOT NULL
);

-- The full hierarchy ORGANIZATION -> PROPERTY -> FLOOR -> ROOM -> BED lives in
-- this one polymorphic table; facility_type_id distinguishes the level and an
-- organization is itself a facility row (its facility_id doubles as the
-- organization_id used across every other table).
CREATE TABLE facility (
    facility_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_code    VARCHAR(30),
    organization_id  BIGINT,
    facility_type_id VARCHAR(30)  NOT NULL,
    facility_name    VARCHAR(150) NOT NULL,
    -- For ORGANIZATION rows this is the sender / Reply-To address for tenant
    -- email. Nullable in the schema; mandatory only at org-creation time, which
    -- the API layer enforces.
    email            VARCHAR(160),
    status           VARCHAR(30)  NOT NULL DEFAULT 'ACTIVE',
    sharing_type     VARCHAR(50),
    capacity         INT,
    description      VARCHAR(1000),
    room_number      VARCHAR(30),
    floor_number     INT,
    monthly_rent     DECIMAL(12,2),
    security_deposit DECIMAL(12,2),
    size_sq_ft       DECIMAL(10,2),
    available_from   DATE,
    version          BIGINT       NOT NULL DEFAULT 0,
    amenities_json   JSONB,
    photos_count     INT DEFAULT 0,
    is_ac            BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMP(6) NOT NULL,
    updated_at       TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_facility_code UNIQUE (facility_code),
    CONSTRAINT fk_facility_org FOREIGN KEY (organization_id) REFERENCES facility (facility_id)
);

CREATE INDEX idx_facility_org_type ON facility (organization_id, facility_type_id);

-- facility_code is matched case-insensitively (BulkUploadController.findFacilityByCode /
-- findChildByCode), because under MySQL's ai_ci collation it always was: re-uploading a CSV
-- with "flr_a" resolved to the existing "FLR_A" instead of creating a second floor. This
-- index enforces the same uniqueness the old UNIQUE constraint gave under that collation --
-- uq_facility_code above only stops byte-identical duplicates -- and keeps those lookups
-- index scans.
CREATE UNIQUE INDEX uk_facility_code_lower ON facility (LOWER(facility_code));

CREATE TABLE person (
    party_id                   BIGINT PRIMARY KEY,
    full_name                  VARCHAR(150) NOT NULL,
    mobile_number              VARCHAR(20)  NOT NULL,
    email                      VARCHAR(120),
    gender                     VARCHAR(20),
    date_of_birth              DATE,
    aadhaar_number             VARCHAR(20),
    occupation                 VARCHAR(100),
    company_name               VARCHAR(150),
    employer_name              VARCHAR(200),
    designation                VARCHAR(120),
    work_address               VARCHAR(500),
    guardian_name              VARCHAR(150),
    guardian_mobile_number     VARCHAR(20),
    emergency_contact_name     VARCHAR(120),
    emergency_contact_mobile   VARCHAR(10),
    emergency_contact_relation VARCHAR(60),
    address                    VARCHAR(500),
    permanent_address          VARCHAR(500),
    has_vehicle                BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at                 TIMESTAMP(6) NOT NULL,
    updated_at                 TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_person_party FOREIGN KEY (party_id) REFERENCES party (party_id)
);

-- Mobile uniqueness is NOT enforced here. V10 added a global unique key and V12
-- removed it again: the same mobile may be an active tenant at two different
-- properties, so uniqueness is property-scoped and lives in application code
-- (TenantService.create / PersonRepository.countActiveTenantsByMobileAtProperty).

-- Parent/child edges of the facility tree, dated so history survives a move.
CREATE TABLE facility_group_member (
    facility_group_member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_facility_id       BIGINT NOT NULL,
    child_facility_id        BIGINT NOT NULL,
    from_date                DATE   NOT NULL,
    thru_date                DATE,
    created_at               TIMESTAMP(6) NOT NULL,
    updated_at               TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_facility_group_active UNIQUE (parent_facility_id, child_facility_id, from_date),
    CONSTRAINT fk_fgm_parent FOREIGN KEY (parent_facility_id) REFERENCES facility (facility_id),
    CONSTRAINT fk_fgm_child  FOREIGN KEY (child_facility_id)  REFERENCES facility (facility_id)
);


-- =============================================================================
-- SECTION 2 -- Authentication
-- =============================================================================

CREATE TABLE user_login (
    user_login_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id             BIGINT       NOT NULL,
    username             VARCHAR(120) NOT NULL UNIQUE,
    password_hash        VARCHAR(255) NOT NULL,
    role_type_id         VARCHAR(30)  NOT NULL,
    organization_id      BIGINT,
    status               VARCHAR(30)  NOT NULL DEFAULT 'ACTIVE',
    -- Why a login is INACTIVE (CHECKED_OUT, ARCHIVED, ...).
    disabled_reason      VARCHAR(40),
    -- Forces a first-login password change; set with the temp password abc@123.
    must_change_password BOOLEAN      NOT NULL DEFAULT FALSE,
    last_login_at        TIMESTAMP(6),
    created_at           TIMESTAMP(6) NOT NULL,
    updated_at           TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_user_party FOREIGN KEY (party_id)        REFERENCES party (party_id),
    CONSTRAINT fk_user_org   FOREIGN KEY (organization_id) REFERENCES facility (facility_id)
);

-- Usernames are matched case-insensitively (MySQL's utf8mb4_0900_ai_ci did this
-- implicitly; PostgreSQL does not). AuthService lowercases both sides of the
-- lookup, and this index is what keeps that lookup an index scan.
CREATE UNIQUE INDEX uk_user_login_username_lower ON user_login (LOWER(username));

CREATE TABLE refresh_token (
    refresh_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_login_id    BIGINT       NOT NULL,
    token_hash       VARCHAR(255) NOT NULL UNIQUE,
    expires_at       TIMESTAMP(6) NOT NULL,
    revoked          BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMP(6) NOT NULL,
    updated_at       TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_refresh_user FOREIGN KEY (user_login_id) REFERENCES user_login (user_login_id)
);

CREATE TABLE password_reset_token (
    password_reset_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_login_id           BIGINT       NOT NULL,
    token_hash              VARCHAR(255) NOT NULL UNIQUE,
    expires_at              TIMESTAMP(6) NOT NULL,
    used_at                 TIMESTAMP(6),
    created_at              TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_password_reset_user FOREIGN KEY (user_login_id) REFERENCES user_login (user_login_id)
);

CREATE TABLE user_device (
    user_device_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_login_id          BIGINT       NOT NULL,
    device_identifier_hash VARCHAR(255) NOT NULL,
    platform               VARCHAR(30)  NOT NULL,
    biometric_enabled      BOOLEAN      NOT NULL DEFAULT FALSE,
    push_token             VARCHAR(500),
    last_seen_at           TIMESTAMP(6) NOT NULL,
    revoked_at             TIMESTAMP(6),
    CONSTRAINT uk_user_device UNIQUE (user_login_id, device_identifier_hash),
    CONSTRAINT fk_user_device_user FOREIGN KEY (user_login_id) REFERENCES user_login (user_login_id)
);

CREATE TABLE user_preference (
    user_login_id    BIGINT       NOT NULL,
    preference_key   VARCHAR(80)  NOT NULL,
    preference_value VARCHAR(1000),
    updated_at       TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (user_login_id, preference_key),
    CONSTRAINT fk_preference_user FOREIGN KEY (user_login_id) REFERENCES user_login (user_login_id)
);


-- =============================================================================
-- SECTION 3 -- Roles and permissions
--
-- role_type is read by the application (RoleType constants must resolve);
-- permission / role_permission are reference data that nothing enforces at
-- runtime -- authorization is @PreAuthorize plus PropertyAccessGuard.
-- =============================================================================

CREATE TABLE role_type (
    role_type_id        VARCHAR(40)  PRIMARY KEY,
    description         VARCHAR(160) NOT NULL,
    parent_role_type_id VARCHAR(40),
    CONSTRAINT fk_role_type_parent FOREIGN KEY (parent_role_type_id) REFERENCES role_type (role_type_id)
);

CREATE TABLE permission (
    permission_id VARCHAR(80)  PRIMARY KEY,
    module_code   VARCHAR(40)  NOT NULL,
    description   VARCHAR(200) NOT NULL
);

CREATE TABLE role_permission (
    role_type_id  VARCHAR(40) NOT NULL,
    permission_id VARCHAR(80) NOT NULL,
    -- LOCALTIMESTAMP, not CURRENT_TIMESTAMP: the latter is timestamptz in
    -- PostgreSQL and would be implicitly cast into this timestamp column.
    from_date     TIMESTAMP(6) NOT NULL DEFAULT LOCALTIMESTAMP(6),
    thru_date     TIMESTAMP(6),
    PRIMARY KEY (role_type_id, permission_id, from_date),
    CONSTRAINT fk_role_permission_role       FOREIGN KEY (role_type_id)  REFERENCES role_type (role_type_id),
    CONSTRAINT fk_role_permission_permission FOREIGN KEY (permission_id) REFERENCES permission (permission_id)
);


-- =============================================================================
-- SECTION 4 -- Occupancy
-- =============================================================================

-- Links a party to a facility with a role over a date range. Active rows have a
-- NULL thru_date. Roles: TENANT (org- and property-level membership), OCCUPANT
-- (a bed), TEMP_OCCUPANT (a temporary stay), PROPERTY_MANAGER (a scoped login's
-- property assignment).
--
-- A temp stay overloads the generic columns rather than getting its own table:
-- from_date = check-in, expected_checkout_date = planned check-out, thru_date =
-- actual check-out, monthly_rent = the editable TOTAL charge for the stay.
CREATE TABLE facility_party (
    facility_party_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id        BIGINT      NOT NULL,
    facility_id            BIGINT      NOT NULL,
    party_id               BIGINT      NOT NULL,
    role_type_id           VARCHAR(30) NOT NULL,
    from_date              DATE        NOT NULL,
    thru_date              DATE,
    expected_checkout_date DATE,
    -- The ALL-IN monthly amount (base rent + AC), so billing totals are the same
    -- everywhere. ac_charges only annotates how much of that total is the AC
    -- premium, which lets an invoice itemize MONTHLY_RENT + AC_CHARGES instead of
    -- one lump sum. Changing either must not change monthly_rent's meaning.
    monthly_rent           DECIMAL(10,2),
    ac_charges             DECIMAL(10,2),
    security_deposit       DECIMAL(10,2),
    created_at             TIMESTAMP(6) NOT NULL,
    updated_at             TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_fp_org      FOREIGN KEY (organization_id) REFERENCES facility (facility_id),
    CONSTRAINT fk_fp_facility FOREIGN KEY (facility_id)     REFERENCES facility (facility_id),
    CONSTRAINT fk_fp_party    FOREIGN KEY (party_id)        REFERENCES party (party_id)
);

CREATE INDEX idx_facility_party_org      ON facility_party (organization_id);
CREATE INDEX idx_facility_party_facility ON facility_party (facility_id);
CREATE INDEX idx_facility_party_party    ON facility_party (party_id);

-- The two composite indexes that matter (added as V23 against MySQL). Every
-- tenant-list query filters on a combination of (organization_id,
-- facility_id|party_id, role_type_id, thru_date); with only the single-column
-- indexes above the planner could use one column and filtered the rest in memory.
CREATE INDEX idx_fp_org_facility_role_thru ON facility_party (organization_id, facility_id, role_type_id, thru_date);
CREATE INDEX idx_fp_org_party_role_thru    ON facility_party (organization_id, party_id,    role_type_id, thru_date);

-- A sharing-type change is never applied mid-cycle. It is recorded here and
-- applied on effective_date (the tenant's next billing anniversary) by
-- BedTransferScheduler, so the current month's invoice is untouched and the new
-- rent starts with the next cycle. Same-sharing transfers apply inline and never
-- create a row here.
CREATE TABLE scheduled_bed_transfer (
    scheduled_bed_transfer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id           BIGINT      NOT NULL,
    party_id                  BIGINT      NOT NULL,
    from_bed_facility_id      BIGINT,
    to_bed_facility_id        BIGINT      NOT NULL,
    effective_date            DATE        NOT NULL,
    new_monthly_rent          DECIMAL(10,2),
    new_security_deposit      DECIMAL(10,2),
    status                    VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    note                      VARCHAR(255),
    created_at                TIMESTAMP(6) NOT NULL,
    updated_at                TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_sbt_due    ON scheduled_bed_transfer (status, effective_date);
CREATE INDEX idx_sbt_party  ON scheduled_bed_transfer (organization_id, party_id, status);
CREATE INDEX idx_sbt_to_bed ON scheduled_bed_transfer (to_bed_facility_id, status);

CREATE TABLE admission (
    admission_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id    BIGINT       NOT NULL,
    party_id           BIGINT       NOT NULL,
    bed_facility_id    BIGINT       NOT NULL,
    move_in_date       DATE         NOT NULL,
    monthly_rent       DECIMAL(12,2) NOT NULL,
    security_deposit   DECIMAL(12,2) NOT NULL DEFAULT 0,
    advance_amount     DECIMAL(12,2) NOT NULL DEFAULT 0,
    notice_period_days INT          NOT NULL DEFAULT 30,
    status             VARCHAR(30)  NOT NULL DEFAULT 'DRAFT',
    created_at         TIMESTAMP(6) NOT NULL,
    updated_at         TIMESTAMP(6) NOT NULL,
    version            BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT fk_admission_org   FOREIGN KEY (organization_id) REFERENCES facility (facility_id),
    CONSTRAINT fk_admission_party FOREIGN KEY (party_id)        REFERENCES party (party_id),
    CONSTRAINT fk_admission_bed   FOREIGN KEY (bed_facility_id) REFERENCES facility (facility_id)
);

CREATE INDEX idx_admission_org_status ON admission (organization_id, status);

CREATE TABLE agreement (
    agreement_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id   BIGINT      NOT NULL,
    admission_id      BIGINT      NOT NULL,
    agreement_type_id VARCHAR(40) NOT NULL DEFAULT 'ACCOMMODATION',
    agreement_number  VARCHAR(80) NOT NULL,
    from_date         DATE        NOT NULL,
    thru_date         DATE,
    terms             TEXT,
    status            VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    signed_at         TIMESTAMP(6),
    created_at        TIMESTAMP(6) NOT NULL,
    updated_at        TIMESTAMP(6) NOT NULL,
    version           BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT uk_agreement_org_number UNIQUE (organization_id, agreement_number),
    CONSTRAINT fk_agreement_org       FOREIGN KEY (organization_id) REFERENCES facility (facility_id),
    CONSTRAINT fk_agreement_admission FOREIGN KEY (admission_id)    REFERENCES admission (admission_id)
);

CREATE TABLE checkout (
    checkout_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id    BIGINT       NOT NULL,
    admission_id       BIGINT       NOT NULL,
    checkout_date      DATE         NOT NULL,
    pending_dues       DECIMAL(12,2) NOT NULL DEFAULT 0,
    damage_charges     DECIMAL(12,2) NOT NULL DEFAULT 0,
    other_deductions   DECIMAL(12,2) NOT NULL DEFAULT 0,
    refundable_deposit DECIMAL(12,2) NOT NULL DEFAULT 0,
    status             VARCHAR(30)  NOT NULL DEFAULT 'PENDING',
    refund_method      VARCHAR(30),
    refund_reference   VARCHAR(120),
    settled_at         TIMESTAMP(6),
    created_at         TIMESTAMP(6) NOT NULL,
    updated_at         TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_checkout_admission UNIQUE (admission_id),
    CONSTRAINT fk_checkout_org       FOREIGN KEY (organization_id) REFERENCES facility (facility_id),
    CONSTRAINT fk_checkout_admission FOREIGN KEY (admission_id)    REFERENCES admission (admission_id)
);


-- =============================================================================
-- SECTION 5 -- Tenant profile detail
-- =============================================================================

CREATE TABLE tenant_employment (
    tenant_employment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id      BIGINT       NOT NULL,
    party_id             BIGINT       NOT NULL,
    company_name         VARCHAR(160),
    designation          VARCHAR(120),
    employee_id          VARCHAR(80),
    monthly_salary       DECIMAL(12,2),
    work_email           VARCHAR(160),
    office_address       VARCHAR(500),
    from_date            DATE         NOT NULL,
    thru_date            DATE,
    created_at           TIMESTAMP(6) NOT NULL,
    updated_at           TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_employment_org   FOREIGN KEY (organization_id) REFERENCES facility (facility_id),
    CONSTRAINT fk_employment_party FOREIGN KEY (party_id)        REFERENCES party (party_id)
);

CREATE INDEX idx_employment_tenant ON tenant_employment (organization_id, party_id, thru_date);

CREATE TABLE emergency_contact (
    emergency_contact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id      BIGINT       NOT NULL,
    party_id             BIGINT       NOT NULL,
    contact_name         VARCHAR(150) NOT NULL,
    relationship_type_id VARCHAR(40)  NOT NULL,
    mobile_number        VARCHAR(20)  NOT NULL,
    alternate_number     VARCHAR(20),
    address              VARCHAR(500),
    is_primary           BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMP(6) NOT NULL,
    updated_at           TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_emergency_org   FOREIGN KEY (organization_id) REFERENCES facility (facility_id),
    CONSTRAINT fk_emergency_party FOREIGN KEY (party_id)        REFERENCES party (party_id)
);

CREATE INDEX idx_emergency_party ON emergency_contact (organization_id, party_id);

-- content_reference_id is deliberately absent: V24 dropped the content_reference
-- table (document storage was never wired up) along with this column.
CREATE TABLE identity_document (
    identity_document_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id      BIGINT      NOT NULL,
    party_id             BIGINT      NOT NULL,
    document_type_id     VARCHAR(40) NOT NULL,
    document_number      VARCHAR(120),
    verification_status  VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    verified_at          TIMESTAMP(6),
    expires_on           DATE,
    created_at           TIMESTAMP(6) NOT NULL,
    updated_at           TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_identity_org_party_type UNIQUE (organization_id, party_id, document_type_id),
    CONSTRAINT fk_identity_org   FOREIGN KEY (organization_id) REFERENCES facility (facility_id),
    CONSTRAINT fk_identity_party FOREIGN KEY (party_id)        REFERENCES party (party_id)
);

-- The owner-facing "Delete tenant", which never loses data. Nothing is removed
-- from party / person / facility_party / invoice / payment -- a row lands here and
-- the tenant drops out of the lists. Exactly ONE live row per party, and restore
-- DELETES it rather than flagging it, so "is this tenant hidden?" stays a plain
-- existence check; the history lives in audit_log (TENANT_ARCHIVED /
-- TENANT_RESTORED). property_facility_id has no FK on purpose: a property can be
-- removed while its archived tenants remain.
CREATE TABLE tenant_archive (
    tenant_archive_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id           BIGINT       NOT NULL,
    property_facility_id      BIGINT,
    party_id                  BIGINT       NOT NULL,
    full_name                 VARCHAR(150),
    mobile_number             VARCHAR(20),
    archived_at               TIMESTAMP(6) NOT NULL,
    archived_by_user_login_id BIGINT,
    created_at                TIMESTAMP(6) NOT NULL,
    updated_at                TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_tenant_archive_party UNIQUE (party_id),
    CONSTRAINT fk_tenant_archive_org   FOREIGN KEY (organization_id) REFERENCES facility (facility_id),
    CONSTRAINT fk_tenant_archive_party FOREIGN KEY (party_id)        REFERENCES party (party_id)
);

CREATE INDEX idx_tenant_archive_org_property ON tenant_archive (organization_id, property_facility_id);


-- =============================================================================
-- SECTION 6 -- Amenities
-- =============================================================================

CREATE TABLE amenity_type (
    amenity_type_id VARCHAR(40)  PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    icon_code       VARCHAR(60),
    active          BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE facility_amenity (
    facility_id     BIGINT      NOT NULL,
    amenity_type_id VARCHAR(40) NOT NULL,
    available       BOOLEAN     NOT NULL DEFAULT TRUE,
    details         VARCHAR(500),
    PRIMARY KEY (facility_id, amenity_type_id),
    CONSTRAINT fk_fa_facility FOREIGN KEY (facility_id)     REFERENCES facility (facility_id),
    CONSTRAINT fk_fa_type     FOREIGN KEY (amenity_type_id) REFERENCES amenity_type (amenity_type_id)
);


-- =============================================================================
-- SECTION 7 -- Pricing
-- =============================================================================

-- Price Master: per property + sharing type. OccupancyService.resolveRent walks
-- BED -> ROOM -> FLOOR -> PROPERTY and reads this table directly (never the
-- SHARING_PRICES cache) so an assignment always prices off fresh data.
CREATE TABLE property_sharing_price (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id      BIGINT        NOT NULL,
    property_facility_id BIGINT        NOT NULL,
    sharing_type         VARCHAR(5)    NOT NULL,
    monthly_rent         DECIMAL(10,2) NOT NULL,
    security_deposit     DECIMAL(10,2) NOT NULL DEFAULT 0,
    ac_charges           DECIMAL(10,2) NOT NULL DEFAULT 0,
    -- Per-day rate for temporary stays: amount = days * per_day_price, editable
    -- by the owner before the single TEMP_STAY invoice is raised.
    per_day_price        DECIMAL(10,2) NOT NULL DEFAULT 0,
    CONSTRAINT uk_prop_sharing UNIQUE (property_facility_id, sharing_type),
    CONSTRAINT fk_psp_facility FOREIGN KEY (property_facility_id) REFERENCES facility (facility_id)
);


-- =============================================================================
-- SECTION 8 -- Billing
-- =============================================================================

-- Legacy per-month rent charge. Superseded by invoice/billing_account but still
-- mapped by the Rent entity and still the target of invoice.legacy_rent_id.
CREATE TABLE rent (
    rent_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT      NOT NULL,
    party_id        BIGINT      NOT NULL,
    facility_id     BIGINT,
    rent_month      DATE        NOT NULL,
    monthly_rent    DECIMAL(12,2) NOT NULL DEFAULT 0,
    deposit         DECIMAL(12,2) NOT NULL DEFAULT 0,
    advance         DECIMAL(12,2) NOT NULL DEFAULT 0,
    discount        DECIMAL(12,2) NOT NULL DEFAULT 0,
    penalty         DECIMAL(12,2) NOT NULL DEFAULT 0,
    paid_amount     DECIMAL(12,2) NOT NULL DEFAULT 0,
    status          VARCHAR(30)  NOT NULL DEFAULT 'PENDING',
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_rent_org      FOREIGN KEY (organization_id) REFERENCES facility (facility_id),
    CONSTRAINT fk_rent_party    FOREIGN KEY (party_id)        REFERENCES party (party_id),
    CONSTRAINT fk_rent_facility FOREIGN KEY (facility_id)     REFERENCES facility (facility_id)
);

CREATE INDEX idx_rent_org_month ON rent (organization_id, rent_month);

CREATE TABLE payment (
    payment_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id         BIGINT      NOT NULL,
    rent_id                 BIGINT,
    party_id                BIGINT      NOT NULL,
    amount                  DECIMAL(12,2) NOT NULL,
    payment_mode            VARCHAR(30) NOT NULL,
    payment_date            DATE        NOT NULL,
    reference_number        VARCHAR(120),
    notes                   VARCHAR(500),
    -- Client-generated UUID that makes payment collection safe to retry.
    idempotency_key         VARCHAR(100),
    provider_code           VARCHAR(40),
    external_transaction_id VARCHAR(160),
    status                  VARCHAR(30) NOT NULL DEFAULT 'RECEIVED',
    created_at              TIMESTAMP(6) NOT NULL,
    updated_at              TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_payment_org   FOREIGN KEY (organization_id) REFERENCES facility (facility_id),
    CONSTRAINT fk_payment_rent  FOREIGN KEY (rent_id)         REFERENCES rent (rent_id),
    CONSTRAINT fk_payment_party FOREIGN KEY (party_id)        REFERENCES party (party_id)
);

CREATE INDEX idx_payment_org_date ON payment (organization_id, payment_date);
-- Unique across non-NULL keys only; both MySQL and PostgreSQL allow unlimited
-- NULLs in a unique index, so payments without an idempotency key are unaffected.
CREATE UNIQUE INDEX uk_payment_org_idempotency ON payment (organization_id, idempotency_key);

CREATE TABLE billing_account (
    billing_account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id    BIGINT      NOT NULL,
    party_id           BIGINT      NOT NULL,
    admission_id       BIGINT,
    currency_code      VARCHAR(3)  NOT NULL DEFAULT 'INR',
    status             VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    advance_balance    DECIMAL(12,2) NOT NULL DEFAULT 0,
    created_at         TIMESTAMP(6) NOT NULL,
    updated_at         TIMESTAMP(6) NOT NULL,
    version            BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT fk_billing_org       FOREIGN KEY (organization_id) REFERENCES facility (facility_id),
    CONSTRAINT fk_billing_party     FOREIGN KEY (party_id)        REFERENCES party (party_id),
    CONSTRAINT fk_billing_admission FOREIGN KEY (admission_id)    REFERENCES admission (admission_id)
);

CREATE INDEX idx_billing_party ON billing_account (organization_id, party_id, status);

CREATE TABLE invoice (
    invoice_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id       BIGINT      NOT NULL,
    billing_account_id    BIGINT      NOT NULL,
    legacy_rent_id        BIGINT,
    invoice_number        VARCHAR(80) NOT NULL,
    invoice_month         DATE        NOT NULL,
    issue_date            DATE        NOT NULL,
    due_date              DATE        NOT NULL,
    total_amount          DECIMAL(12,2) NOT NULL DEFAULT 0,
    paid_amount           DECIMAL(12,2) NOT NULL DEFAULT 0,
    status                VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    notification_sent     BOOLEAN     NOT NULL DEFAULT FALSE,
    last_reminder_sent_at TIMESTAMP(6),
    created_at            TIMESTAMP(6) NOT NULL,
    updated_at            TIMESTAMP(6) NOT NULL,
    version               BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT uk_invoice_org_number   UNIQUE (organization_id, invoice_number),
    CONSTRAINT uk_invoice_legacy_rent  UNIQUE (legacy_rent_id),
    CONSTRAINT fk_invoice_org     FOREIGN KEY (organization_id)    REFERENCES facility (facility_id),
    CONSTRAINT fk_invoice_account FOREIGN KEY (billing_account_id) REFERENCES billing_account (billing_account_id),
    CONSTRAINT fk_invoice_legacy  FOREIGN KEY (legacy_rent_id)     REFERENCES rent (rent_id)
);

CREATE INDEX idx_invoice_org_month_status ON invoice (organization_id, invoice_month, status);

CREATE TABLE invoice_item (
    invoice_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id      BIGINT      NOT NULL,
    -- MONTHLY_RENT (base = rent - AC) | AC_CHARGES | SECURITY_DEPOSIT (move-in
    -- invoice only) | TEMP_STAY | OTHER.
    item_type_id    VARCHAR(40) NOT NULL,
    description     VARCHAR(200) NOT NULL,
    amount          DECIMAL(12,2) NOT NULL,
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_invoice_item_invoice FOREIGN KEY (invoice_id) REFERENCES invoice (invoice_id)
);

CREATE TABLE payment_allocation (
    payment_allocation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id       BIGINT      NOT NULL,
    payment_id            BIGINT      NOT NULL,
    invoice_id            BIGINT      NOT NULL,
    amount                DECIMAL(12,2) NOT NULL,
    allocated_at          TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_payment_invoice UNIQUE (payment_id, invoice_id),
    CONSTRAINT fk_allocation_org     FOREIGN KEY (organization_id) REFERENCES facility (facility_id),
    CONSTRAINT fk_allocation_payment FOREIGN KEY (payment_id)      REFERENCES payment (payment_id),
    CONSTRAINT fk_allocation_invoice FOREIGN KEY (invoice_id)      REFERENCES invoice (invoice_id)
);

CREATE TABLE payment_refund (
    payment_refund_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id   BIGINT      NOT NULL,
    payment_id        BIGINT      NOT NULL,
    amount            DECIMAL(12,2) NOT NULL,
    refund_method     VARCHAR(30) NOT NULL DEFAULT 'CASH',
    reference_number  VARCHAR(120),
    reason            VARCHAR(500),
    status            VARCHAR(30) NOT NULL DEFAULT 'RECORDED',
    refunded_at       TIMESTAMP(6) NOT NULL,
    created_at        TIMESTAMP(6) NOT NULL,
    updated_at        TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_refund_org     FOREIGN KEY (organization_id) REFERENCES facility (facility_id),
    CONSTRAINT fk_refund_payment FOREIGN KEY (payment_id)      REFERENCES payment (payment_id)
);

-- Per-organization invoice automation. A MISSING ROW MEANS DEFAULTS (lead 1 day,
-- grace 2 days, auto ON), so a new org is automated with no backfill.
-- Read/written by BillingConfigService via JdbcTemplate -- deliberately not a JPA
-- entity, so ddl-auto=validate does not track it.
CREATE TABLE organization_billing_config (
    organization_billing_config_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id                BIGINT  NOT NULL,
    -- How many days BEFORE the tenant's billing anniversary the invoice is raised.
    invoice_lead_days              INT     NOT NULL DEFAULT 1,
    -- How many days AFTER the due date a freshly raised invoice still counts as
    -- unconsumed, so a tenant checking out in that window has it deleted rather
    -- than billed for a month they did not stay.
    checkout_grace_days            INT     NOT NULL DEFAULT 2,
    auto_generate_enabled          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at                     TIMESTAMP(6) NOT NULL,
    updated_at                     TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_org_billing_config UNIQUE (organization_id),
    CONSTRAINT fk_org_billing_config_org FOREIGN KEY (organization_id) REFERENCES facility (facility_id)
);


-- =============================================================================
-- SECTION 9 -- Expenses, petty cash and staff
-- =============================================================================

-- Categories, vendors and approvals are deliberately NOT master tables:
-- categories are VARCHAR constants in code (mirrored once in the Flutter app),
-- a vendor is an optional party FK or free text, and approval is the status
-- column. See docs/EXPENSES_SCHEMA_MAPPING.md.
CREATE TABLE expense (
    expense_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id      BIGINT       NOT NULL,
    property_facility_id BIGINT,                                  -- NULL = org-level
    category             VARCHAR(30)  NOT NULL,
    title                VARCHAR(120) NOT NULL,
    description          VARCHAR(500),
    amount               DECIMAL(12,2) NOT NULL,
    expense_date         DATE         NOT NULL,
    payment_method       VARCHAR(20)  NOT NULL DEFAULT 'CASH',    -- CASH | UPI | CARD | BANK_TRANSFER
    vendor_party_id      BIGINT,
    vendor_name          VARCHAR(120),
    status               VARCHAR(20)  NOT NULL DEFAULT 'PENDING', -- PENDING | APPROVED | REJECTED | PAID
    approved_by          BIGINT,                                  -- user_login_id
    approved_at          TIMESTAMP(6),
    created_by           BIGINT,                                  -- user_login_id
    created_at           TIMESTAMP(6) NOT NULL,
    updated_at           TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_expense_org_date   ON expense (organization_id, expense_date);
CREATE INDEX idx_expense_prop_date  ON expense (property_facility_id, expense_date);
CREATE INDEX idx_expense_org_status ON expense (organization_id, status);
CREATE INDEX idx_expense_org_cat    ON expense (organization_id, category, expense_date);

-- Sentinel scoping keeps the unique key enforceable (a unique index ignores
-- NULLs): property_facility_id = 0 means "whole org", category = 'ALL' means the
-- overall monthly budget shown on the summary card.
CREATE TABLE expense_budget (
    expense_budget_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id      BIGINT      NOT NULL,
    property_facility_id BIGINT      NOT NULL DEFAULT 0,
    category             VARCHAR(30) NOT NULL DEFAULT 'ALL',
    budget_month         VARCHAR(7)  NOT NULL,                    -- 'YYYY-MM'
    amount               DECIMAL(12,2) NOT NULL,
    created_at           TIMESTAMP(6) NOT NULL,
    updated_at           TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_budget_scope UNIQUE (organization_id, property_facility_id, category, budget_month)
);

-- OUT rows are written automatically when a CASH expense is approved (expense_id
-- set); IN rows are manual top-ups. Balances are a running sum, never stored.
CREATE TABLE petty_cash_entry (
    petty_cash_entry_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id      BIGINT      NOT NULL,
    property_facility_id BIGINT      NOT NULL DEFAULT 0,
    entry_type           VARCHAR(10) NOT NULL,                    -- IN | OUT
    amount               DECIMAL(12,2) NOT NULL,
    note                 VARCHAR(255),
    entry_date           DATE        NOT NULL,
    expense_id           BIGINT,
    created_by           BIGINT,
    created_at           TIMESTAMP(6) NOT NULL,
    updated_at           TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_pce_scope_date ON petty_cash_entry (organization_id, property_facility_id, entry_date);

-- Staff have no logins and no tenancy, so this deliberately does not reuse
-- party/person. Paying a salary also writes a SALARY expense, linked back
-- through staff_salary_payment.expense_id.
CREATE TABLE staff (
    staff_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id      BIGINT       NOT NULL,
    property_facility_id BIGINT,                                  -- NULL = org-level
    full_name            VARCHAR(120) NOT NULL,
    profession           VARCHAR(60)  NOT NULL,
    mobile_number        VARCHAR(15),
    monthly_salary       DECIMAL(12,2) NOT NULL,
    join_date            DATE,
    status               VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',  -- ACTIVE | INACTIVE
    notes                VARCHAR(255),
    created_at           TIMESTAMP(6) NOT NULL,
    updated_at           TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_staff_org  ON staff (organization_id, status);
CREATE INDEX idx_staff_prop ON staff (property_facility_id, status);

CREATE TABLE staff_salary_payment (
    staff_salary_payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id         BIGINT      NOT NULL,
    staff_id                BIGINT      NOT NULL,
    pay_month               VARCHAR(7)  NOT NULL,                 -- 'YYYY-MM'
    amount                  DECIMAL(12,2) NOT NULL,
    payment_method          VARCHAR(20) NOT NULL DEFAULT 'CASH',
    paid_date               DATE        NOT NULL,
    expense_id              BIGINT,
    created_by              BIGINT,
    created_at              TIMESTAMP(6) NOT NULL,
    updated_at              TIMESTAMP(6) NOT NULL,
    -- The double-payment guard: one row per staff per month.
    CONSTRAINT uk_staff_pay_month UNIQUE (staff_id, pay_month)
);

CREATE INDEX idx_ssp_org_month ON staff_salary_payment (organization_id, pay_month);


-- =============================================================================
-- SECTION 10 -- Notifications
-- =============================================================================

CREATE TABLE notification_category (
    category_id VARCHAR(40)  PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(250),
    active      BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE notification (
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT       NOT NULL,
    category_id     VARCHAR(40)  NOT NULL,
    title           VARCHAR(160) NOT NULL,
    message         VARCHAR(2000) NOT NULL,
    entity_type     VARCHAR(40),
    entity_id       BIGINT,
    priority        VARCHAR(20)  NOT NULL DEFAULT 'NORMAL',
    created_at      TIMESTAMP(6) NOT NULL,
    expires_at      TIMESTAMP(6),
    CONSTRAINT fk_notification_org      FOREIGN KEY (organization_id) REFERENCES facility (facility_id),
    CONSTRAINT fk_notification_category FOREIGN KEY (category_id)     REFERENCES notification_category (category_id)
);

CREATE INDEX idx_notification_org_created ON notification (organization_id, created_at);

CREATE TABLE notification_recipient (
    notification_recipient_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id           BIGINT  NOT NULL,
    party_id                  BIGINT  NOT NULL,
    read_at                   TIMESTAMP(6),
    archived_at               TIMESTAMP(6),
    important                 BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_notification_party UNIQUE (notification_id, party_id),
    CONSTRAINT fk_nr_notification FOREIGN KEY (notification_id) REFERENCES notification (notification_id),
    CONSTRAINT fk_nr_party        FOREIGN KEY (party_id)        REFERENCES party (party_id)
);

-- Read and write sides of the owner gate MUST stay in step. NotificationService.
-- notifyOwners INNER JOINs this table on enabled = TRUE, and
-- NotificationController.preferences() reads COALESCE(p.enabled, FALSE): a missing
-- row means OFF on both sides, so in-app owner notifications are opt-in. Tenant
-- notifications are the opposite (opt-out) because tenants have no preferences UI.
--
-- The column default below is TRUE only because a row is written explicitly with
-- the intended value; it is never relied on to decide delivery.
CREATE TABLE notification_preference (
    party_id        BIGINT      NOT NULL,
    category_id     VARCHAR(40) NOT NULL,
    channel_type_id VARCHAR(30) NOT NULL,
    enabled         BOOLEAN     NOT NULL DEFAULT TRUE,
    updated_at      TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (party_id, category_id, channel_type_id),
    CONSTRAINT fk_np_party    FOREIGN KEY (party_id)    REFERENCES party (party_id),
    CONSTRAINT fk_np_category FOREIGN KEY (category_id) REFERENCES notification_category (category_id)
);

CREATE TABLE notification_outbox (
    outbox_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id     BIGINT      NOT NULL,
    party_id            BIGINT      NOT NULL,
    channel_type_id     VARCHAR(30) NOT NULL,
    provider_code       VARCHAR(40),
    provider_message_id VARCHAR(160),
    status              VARCHAR(30) NOT NULL DEFAULT 'DISABLED',
    attempt_count       INT         NOT NULL DEFAULT 0,
    next_attempt_at     TIMESTAMP(6),
    last_error          VARCHAR(1000),
    created_at          TIMESTAMP(6) NOT NULL,
    updated_at          TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_outbox_notification FOREIGN KEY (notification_id) REFERENCES notification (notification_id),
    CONSTRAINT fk_outbox_party        FOREIGN KEY (party_id)        REFERENCES party (party_id)
);


-- =============================================================================
-- SECTION 11 -- Tenant module: complaints and notices
-- =============================================================================

CREATE TABLE complaint (
    complaint_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id      BIGINT       NOT NULL,
    party_id             BIGINT       NOT NULL,   -- the tenant who raised it
    property_facility_id BIGINT,                  -- resolved from their active bed
    category             VARCHAR(40)  NOT NULL,
    title                VARCHAR(160) NOT NULL,
    description          VARCHAR(2000) NOT NULL,
    priority             VARCHAR(20)  NOT NULL DEFAULT 'MEDIUM',
    status               VARCHAR(20)  NOT NULL DEFAULT 'OPEN',  -- OPEN/IN_PROGRESS/RESOLVED/CLOSED
    created_at           TIMESTAMP(6) NOT NULL,
    updated_at           TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_complaint_org   FOREIGN KEY (organization_id) REFERENCES facility (facility_id),
    CONSTRAINT fk_complaint_party FOREIGN KEY (party_id)        REFERENCES party (party_id)
);

CREATE INDEX idx_complaint_org_party  ON complaint (organization_id, party_id);
CREATE INDEX idx_complaint_org_status ON complaint (organization_id, status);

CREATE TABLE complaint_status_history (
    complaint_status_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_id                BIGINT      NOT NULL,
    from_status                 VARCHAR(20),
    to_status                   VARCHAR(20) NOT NULL,
    note                        VARCHAR(1000),
    changed_by_user_login_id    BIGINT,
    created_at                  TIMESTAMP(6) NOT NULL,
    updated_at                  TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_complaint_history_complaint FOREIGN KEY (complaint_id) REFERENCES complaint (complaint_id)
);

CREATE INDEX idx_complaint_history_complaint ON complaint_status_history (complaint_id);

-- Org-wide when property_facility_id IS NULL.
CREATE TABLE notice (
    notice_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id          BIGINT       NOT NULL,
    property_facility_id     BIGINT,
    notice_type              VARCHAR(30)  NOT NULL DEFAULT 'ANNOUNCEMENT',
    title                    VARCHAR(160) NOT NULL,
    body                     VARCHAR(4000) NOT NULL,
    published_at             TIMESTAMP(6) NOT NULL,
    expires_at               TIMESTAMP(6),
    created_by_user_login_id BIGINT,
    active                   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at               TIMESTAMP(6) NOT NULL,
    updated_at               TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_notice_org FOREIGN KEY (organization_id) REFERENCES facility (facility_id)
);

CREATE INDEX idx_notice_org_active ON notice (organization_id, active);

CREATE TABLE notice_read (
    notice_read_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_id      BIGINT       NOT NULL,
    party_id       BIGINT       NOT NULL,
    read_at        TIMESTAMP(6) NOT NULL,
    created_at     TIMESTAMP(6) NOT NULL,
    updated_at     TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_notice_read UNIQUE (notice_id, party_id),
    CONSTRAINT fk_notice_read_notice FOREIGN KEY (notice_id) REFERENCES notice (notice_id),
    CONSTRAINT fk_notice_read_party  FOREIGN KEY (party_id)  REFERENCES party (party_id)
);


-- =============================================================================
-- SECTION 12 -- Features, subscription and platform settings
-- =============================================================================

CREATE TABLE feature_master (
    feature_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_code VARCHAR(60)  NOT NULL UNIQUE,
    feature_name VARCHAR(120) NOT NULL,
    active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL
);

-- Per-org feature toggles, including the EMAIL / WHATSAPP messaging channels and
-- TENANT_LOGIN. All are OPT-IN: a feature is on for an org only when a row exists
-- here with enabled = TRUE.
CREATE TABLE organization_feature (
    organization_feature_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id         BIGINT  NOT NULL,
    feature_id              BIGINT  NOT NULL,
    enabled                 BOOLEAN NOT NULL DEFAULT FALSE,
    created_at              TIMESTAMP(6) NOT NULL,
    updated_at              TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_org_feature UNIQUE (organization_id, feature_id),
    CONSTRAINT fk_org_feature_org     FOREIGN KEY (organization_id) REFERENCES facility (facility_id),
    CONSTRAINT fk_org_feature_feature FOREIGN KEY (feature_id)      REFERENCES feature_master (feature_id)
);

CREATE TABLE subscription (
    subscription_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT      NOT NULL,
    -- A plain string. The subscription_plan catalogue that once backed it was
    -- dropped (V29) because nothing consumed it; prices come from
    -- property_sharing_price.
    plan_code       VARCHAR(30) NOT NULL,
    start_date      DATE        NOT NULL,
    end_date        DATE        NOT NULL,
    renewal_date    DATE,
    status          VARCHAR(30) NOT NULL,
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_subscription_org FOREIGN KEY (organization_id) REFERENCES facility (facility_id)
);

CREATE TABLE system_setting (
    setting_key              VARCHAR(100) PRIMARY KEY,
    setting_value            VARCHAR(2000),
    encrypted                BOOLEAN      NOT NULL DEFAULT FALSE,
    updated_by_user_login_id BIGINT,
    updated_at               TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_system_setting_user FOREIGN KEY (updated_by_user_login_id) REFERENCES user_login (user_login_id)
);

-- What the platform charges an org per active tenant per month. Two levels, like
-- organization_billing_config: the global default lives in system_setting and
-- this table holds per-org overrides only, so a MISSING ROW means "use the
-- default" and onboarding an org needs no write at all.
CREATE TABLE organization_tenant_rate (
    organization_tenant_rate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id             BIGINT        NOT NULL,
    -- DECIMAL not DOUBLE: this multiplies into an invoice figure and binary
    -- floating point would drift on the totals.
    price_per_tenant            DECIMAL(10,2) NOT NULL,
    updated_by_user_login_id    BIGINT,
    created_at                  TIMESTAMP(6) NOT NULL,
    updated_at                  TIMESTAMP(6) NOT NULL,
    -- One live rate per org: the upsert depends on this, and two rows would make
    -- the Active Tenants report silently non-deterministic.
    CONSTRAINT uk_otr_organization UNIQUE (organization_id),
    CONSTRAINT fk_otr_organization FOREIGN KEY (organization_id) REFERENCES facility (facility_id)
);


-- =============================================================================
-- SECTION 13 -- Audit, bulk upload and API request log
-- =============================================================================

CREATE TABLE audit_log (
    audit_log_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT,
    user_login_id   BIGINT,
    action          VARCHAR(80) NOT NULL,
    entity_type     VARCHAR(80),
    entity_id       VARCHAR(80),
    ip_address      VARCHAR(80),
    details         VARCHAR(1000),
    correlation_id  VARCHAR(100),
    old_values_json JSONB,
    new_values_json JSONB,
    user_agent      VARCHAR(500),
    created_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_audit_org  FOREIGN KEY (organization_id) REFERENCES facility (facility_id),
    CONSTRAINT fk_audit_user FOREIGN KEY (user_login_id)   REFERENCES user_login (user_login_id)
);

CREATE INDEX idx_audit_org_action ON audit_log (organization_id, action);

CREATE TABLE bulk_upload_job (
    job_id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id            BIGINT      NOT NULL,
    upload_type                VARCHAR(30) NOT NULL,
    total_rows                 INT         NOT NULL DEFAULT 0,
    created_rows               INT         NOT NULL DEFAULT 0,
    updated_rows               INT         NOT NULL DEFAULT 0,
    failed_rows                INT         NOT NULL DEFAULT 0,
    performed_by_user_login_id BIGINT      NOT NULL,
    created_at                 TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_upload_job_org  FOREIGN KEY (organization_id)            REFERENCES facility (facility_id),
    CONSTRAINT fk_upload_job_user FOREIGN KEY (performed_by_user_login_id) REFERENCES user_login (user_login_id)
);

-- One row per incoming HTTP hit, written by com.pgmanager.apilog.ApiLogFilter and
-- purged after logging.api.retention-days by ApiLogCleanupScheduler. Column types
-- must stay in step with the ApiRequestLog entity (ddl-auto is `validate`).
--
-- A BIGINT identity PK rather than a UUID: this is the highest-insert-rate table
-- in the schema, and a monotonic key appends to the rightmost index page instead
-- of scattering writes across the whole index.
CREATE TABLE api_request_log (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- All three are NULL for anonymous/rejected traffic, which is a meaningful
    -- value here (it is how you find unauthenticated probing), not a defect.
    organization_id      BIGINT,
    user_login_id        BIGINT,
    tenant_id            BIGINT,

    -- request_id is the client's X-Request-Id when supplied, else a server UUID.
    request_id           VARCHAR(64),
    session_id           VARCHAR(128),

    request_uri          VARCHAR(512) NOT NULL,
    http_method          VARCHAR(10)  NOT NULL,
    controller_name      VARCHAR(160),
    method_name          VARCHAR(120),

    -- Masked, then truncated to logging.api.max-payload-chars (default 8000).
    -- TEXT is unbounded in PostgreSQL, so the cap is purely the application's.
    request_body         TEXT,
    query_parameters     TEXT,
    request_headers      TEXT,

    response_status_code INT,
    response_body        TEXT,

    request_start_time   TIMESTAMP(6) NOT NULL,
    request_end_time     TIMESTAMP(6),
    execution_time_ms    BIGINT,

    -- Flutter device headers.
    platform             VARCHAR(40),
    app_version          VARCHAR(40),
    build_number         VARCHAR(40),
    device_model         VARCHAR(120),
    manufacturer         VARCHAR(80),
    os_name              VARCHAR(40),
    os_version           VARCHAR(40),

    -- 64 chars covers IPv6; only the first X-Forwarded-For hop is stored.
    client_ip_address    VARCHAR(64),
    network_type         VARCHAR(40),
    user_agent           VARCHAR(512),

    -- SUCCESS | FAILED | EXCEPTION | UNAUTHORIZED | FORBIDDEN | TIMEOUT. Stored as
    -- a string, not an ordinal, so adding a value cannot reinterpret old rows.
    status               VARCHAR(20)  NOT NULL,
    error_code           VARCHAR(120),
    error_message        VARCHAR(1000),

    created_date         TIMESTAMP(6) NOT NULL
);

-- Deliberately no foreign keys to facility/user_login. This is append-only
-- diagnostic data written on every request, including for principals that may
-- later be deleted; an FK would add a lock and a lookup to the hottest insert
-- path and could block a legitimate delete elsewhere.

-- The retention sweep and every time-bounded query. The one index that must exist.
CREATE INDEX idx_arl_created_date ON api_request_log (created_date);

-- Composite, not single-column, for the two dimensions that are always sliced by
-- time as well. A lone organization_id index would be near-useless: low
-- cardinality, and the planner would still filter the date range row by row.
CREATE INDEX idx_arl_org_created  ON api_request_log (organization_id, created_date);
CREATE INDEX idx_arl_user_created ON api_request_log (user_login_id, created_date);

-- Endpoint-level analysis: slowest / most-hit URIs.
CREATE INDEX idx_arl_request_uri ON api_request_log (request_uri);

-- Error triage. Both are low cardinality and only really earn their keep combined
-- with the date, but they stay selective for the rare values (EXCEPTION, 500)
-- anyone actually searches for.
CREATE INDEX idx_arl_status               ON api_request_log (status);
CREATE INDEX idx_arl_response_status_code ON api_request_log (response_status_code);

-- "Is the crash only on build 42?" -- release adoption and per-version failure rates.
CREATE INDEX idx_arl_app_version ON api_request_log (app_version);

-- Support flow: a user reports a failure quoting the X-Request-Id from the response.
CREATE INDEX idx_arl_request_id ON api_request_log (request_id);


-- =============================================================================
-- SECTION 14 -- Reference and seed data
--
-- This is the NET result of the seeds in V2, V3, V11, V20, V21, V22 and V31.
-- Rows that were inserted and later deleted (the SMS channel, V20 -> V21) and
-- rows that INSERT IGNORE silently skipped (V11's RENT_REMINDER and V22's
-- COMPLAINT, both already present from V3) are resolved here rather than
-- replayed.
-- =============================================================================

INSERT INTO role_type (role_type_id, description) VALUES
    ('SUPER_ADMIN',      'Platform administrator'),
    ('OWNER',            'Organization owner'),
    ('PROPERTY_MANAGER', 'Property manager'),
    ('MANAGER',          'Manager'),
    ('ACCOUNTANT',       'Accountant'),
    ('SUPPORT',          'Support'),
    ('VIEWER',           'Read-only user'),
    ('TENANT',           'Tenant'),
    ('OCCUPANT',         'Active bed occupant');

INSERT INTO permission (permission_id, module_code, description) VALUES
    ('DASHBOARD_VIEW',  'DASHBOARD', 'View dashboards'),
    ('PROPERTY_MANAGE', 'PROPERTY',  'Manage properties and inventory'),
    ('TENANT_MANAGE',   'TENANT',    'Manage tenants and admissions'),
    ('BILLING_MANAGE',  'BILLING',   'Manage invoices and payments'),
    ('REPORT_VIEW',     'REPORTS',   'View reports'),
    ('SETTINGS_MANAGE', 'SETTINGS',  'Manage organization settings'),
    ('PLATFORM_MANAGE', 'ADMIN',     'Manage the SaaS platform');

INSERT INTO role_permission (role_type_id, permission_id)
    SELECT 'OWNER', permission_id FROM permission WHERE permission_id <> 'PLATFORM_MANAGE';
INSERT INTO role_permission (role_type_id, permission_id)
    SELECT 'SUPER_ADMIN', permission_id FROM permission;

INSERT INTO amenity_type (amenity_type_id, name, icon_code) VALUES
    ('WIFI',         'WiFi',             'wifi'),
    ('POWER_BACKUP', 'Power Backup',     'bolt'),
    ('CCTV',         'CCTV',             'videocam'),
    ('RO_WATER',     'RO Water',         'water_drop'),
    ('PARKING',      'Parking',          'local_parking'),
    ('CLEANING',     'Cleaning',         'cleaning_services'),
    ('FOOD',         'Food',             'restaurant'),
    ('LAUNDRY',      'Laundry',          'local_laundry_service'),
    ('AC',           'Air Conditioning', 'ac_unit');

-- notification.category_id references these. The first seven came from V3, the
-- next four from V11 and NOTICE from V22; the names below are the ones that
-- actually survived (V11/V22 used INSERT IGNORE, so V3's wording won for
-- RENT_REMINDER and COMPLAINT).
INSERT INTO notification_category (category_id, name, description, active) VALUES
    ('RENT_REMINDER',     'Rent reminders',       'Rent due and overdue reminders',                 TRUE),
    ('PAYMENT_UPDATE',    'Payment updates',      'Payments, failures and refunds',                 TRUE),
    ('MAINTENANCE',       'Maintenance alerts',   'Maintenance schedules and updates',              TRUE),
    ('COMPLAINT',         'Complaint updates',    'Complaint status changes',                       TRUE),
    ('TENANT_UPDATE',     'Tenant updates',       'Tenant admission and checkout',                  TRUE),
    ('AGREEMENT',         'Agreements and leases','Agreement lifecycle updates',                    TRUE),
    ('PROMOTION',         'Promotions and offers','Optional promotions',                            TRUE),
    ('CHECKOUT_REMINDER', 'Checkout Reminders',   'Upcoming tenant checkout notifications',         TRUE),
    ('PAYMENT_RECEIPT',   'Payment Receipts',     'Payment confirmation and receipt notifications', TRUE),
    ('CHECK_IN',          'Check-in Welcome',     'New tenant check-in notifications',              TRUE),
    ('GENERAL',           'General',              'General system notifications',                   TRUE),
    ('NOTICE',            'Notices',              'Announcements and property notices',             TRUE);

-- Feature codes an org can be granted. EMAIL and WHATSAPP are the messaging
-- channels; TENANT_LOGIN gates the tenant portal. SMS was seeded by V20 and
-- removed by V21 when the device-SIM reminder feature was retired -- it is
-- intentionally not here.
INSERT INTO feature_master (feature_code, feature_name, active, created_at, updated_at) VALUES
    ('EXPENSE',      'Expense Module',        TRUE, LOCALTIMESTAMP(6), LOCALTIMESTAMP(6)),
    ('STAFF',        'Staff Module',          TRUE, LOCALTIMESTAMP(6), LOCALTIMESTAMP(6)),
    ('NOTIFICATION', 'Notification Module',   TRUE, LOCALTIMESTAMP(6), LOCALTIMESTAMP(6)),
    ('REPORTS',      'Reports Module',        TRUE, LOCALTIMESTAMP(6), LOCALTIMESTAMP(6)),
    ('WHATSAPP',     'WhatsApp Module',       TRUE, LOCALTIMESTAMP(6), LOCALTIMESTAMP(6)),
    ('EMAIL',        'Email Notifications',   TRUE, LOCALTIMESTAMP(6), LOCALTIMESTAMP(6)),
    ('TENANT_LOGIN', 'Tenant Login',          TRUE, LOCALTIMESTAMP(6), LOCALTIMESTAMP(6));

-- The fallback per-tenant platform rate, and the thing an admin edits first. It
-- appears automatically in Admin -> System Settings because that screen renders
-- every system_setting row.
INSERT INTO system_setting (setting_key, setting_value, encrypted, updated_at)
    VALUES ('platform.price_per_active_tenant', '15.00', FALSE, LOCALTIMESTAMP(6));
